version: '3.1'

volumes:
  seismic-data-files:

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-admin}
      - POSTGRES_USER=${DATABASE_USER:-admin}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-mysecretpassword}
    ports:
      - 5432:5432

  db-test:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-admin}
      - POSTGRES_USER=${DATABASE_USER:-admin}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-mysecretpassword}
    ports:
      - 5431:5432

  server:
    build:
      context: ./server
    depends_on:
      - db
    volumes:
      - seismic-data-files:/home/server/static
    environment:
      - SECRET=${SECRET}
      - DATABASE_NAME=${DATABASE_NAME:-admin}
      - DATABASE_USER=${DATABASE_USER:-admin}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-mysecretpassword}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - FLASK_ENV=${FLASK_ENV:-DEVELOPMENT}
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  data-view:
    build:
      context: ./data-view
    environment:
      - FLASK_ENV=${FLASK_ENV:-DEVELOPMENT}
      - API_URL=${API_URL:-http://host.docker.internal:5000}
    volumes:
      - seismic-data-files:/home/server/static
    ports:
      - "5006:5006"

  workspace:
    build:
      context: .
      dockerfile: workspace/dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:5000}
        - VITE_VISUALIZER_URL=${VITE_VISUALIZER_URL:-http://localhost:5006}
    ports:
      - "4173:4173"

  admin:
    build:
      context: .
      dockerfile: admin/dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:5000}
    ports:
      - "4172:4173"
