/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlotVelocityModelWorkflowIdRouteImport } from './routes/plot/velocity-model.$workflowId'
import { Route as PlotSampleWorkflowIdRouteImport } from './routes/plot/sample.$workflowId'
import { Route as PlotBasicPlotWorkflowIdRouteImport } from './routes/plot/basic-plot.$workflowId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotVelocityModelWorkflowIdRoute =
  PlotVelocityModelWorkflowIdRouteImport.update({
    id: '/plot/velocity-model/$workflowId',
    path: '/plot/velocity-model/$workflowId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlotSampleWorkflowIdRoute = PlotSampleWorkflowIdRouteImport.update({
  id: '/plot/sample/$workflowId',
  path: '/plot/sample/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotBasicPlotWorkflowIdRoute = PlotBasicPlotWorkflowIdRouteImport.update({
  id: '/plot/basic-plot/$workflowId',
  path: '/plot/basic-plot/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plot/basic-plot/$workflowId': typeof PlotBasicPlotWorkflowIdRoute
  '/plot/sample/$workflowId': typeof PlotSampleWorkflowIdRoute
  '/plot/velocity-model/$workflowId': typeof PlotVelocityModelWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plot/basic-plot/$workflowId': typeof PlotBasicPlotWorkflowIdRoute
  '/plot/sample/$workflowId': typeof PlotSampleWorkflowIdRoute
  '/plot/velocity-model/$workflowId': typeof PlotVelocityModelWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plot/basic-plot/$workflowId': typeof PlotBasicPlotWorkflowIdRoute
  '/plot/sample/$workflowId': typeof PlotSampleWorkflowIdRoute
  '/plot/velocity-model/$workflowId': typeof PlotVelocityModelWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plot/basic-plot/$workflowId'
    | '/plot/sample/$workflowId'
    | '/plot/velocity-model/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plot/basic-plot/$workflowId'
    | '/plot/sample/$workflowId'
    | '/plot/velocity-model/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/plot/basic-plot/$workflowId'
    | '/plot/sample/$workflowId'
    | '/plot/velocity-model/$workflowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlotBasicPlotWorkflowIdRoute: typeof PlotBasicPlotWorkflowIdRoute
  PlotSampleWorkflowIdRoute: typeof PlotSampleWorkflowIdRoute
  PlotVelocityModelWorkflowIdRoute: typeof PlotVelocityModelWorkflowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plot/velocity-model/$workflowId': {
      id: '/plot/velocity-model/$workflowId'
      path: '/plot/velocity-model/$workflowId'
      fullPath: '/plot/velocity-model/$workflowId'
      preLoaderRoute: typeof PlotVelocityModelWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plot/sample/$workflowId': {
      id: '/plot/sample/$workflowId'
      path: '/plot/sample/$workflowId'
      fullPath: '/plot/sample/$workflowId'
      preLoaderRoute: typeof PlotSampleWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plot/basic-plot/$workflowId': {
      id: '/plot/basic-plot/$workflowId'
      path: '/plot/basic-plot/$workflowId'
      fullPath: '/plot/basic-plot/$workflowId'
      preLoaderRoute: typeof PlotBasicPlotWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlotBasicPlotWorkflowIdRoute: PlotBasicPlotWorkflowIdRoute,
  PlotSampleWorkflowIdRoute: PlotSampleWorkflowIdRoute,
  PlotVelocityModelWorkflowIdRoute: PlotVelocityModelWorkflowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
