/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlotSampleWorkflowIdRouteImport } from './routes/plot/sample.$workflowId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotSampleWorkflowIdRoute = PlotSampleWorkflowIdRouteImport.update({
  id: '/plot/sample/$workflowId',
  path: '/plot/sample/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plot/sample/$workflowId': typeof PlotSampleWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plot/sample/$workflowId': typeof PlotSampleWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plot/sample/$workflowId': typeof PlotSampleWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/plot/sample/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plot/sample/$workflowId'
  id: '__root__' | '/' | '/plot/sample/$workflowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlotSampleWorkflowIdRoute: typeof PlotSampleWorkflowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plot/sample/$workflowId': {
      id: '/plot/sample/$workflowId'
      path: '/plot/sample/$workflowId'
      fullPath: '/plot/sample/$workflowId'
      preLoaderRoute: typeof PlotSampleWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlotSampleWorkflowIdRoute: PlotSampleWorkflowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
