from os import path

PICKS_FILE_PATH = path.join(
    path.dirname(__file__),
    'files',
    'marmousi_velstk_picks.dat'
)


def loadMockPicks() -> dict[int, dict[str, list[float]]]:
    """
    ### Reversed picks.dat file generation

    - Reads a sample .dat file, returns python structured data
    - Returns format accepted by the route `/helper-files/generate/<lineId>/table`
        - Return data shall be in the format generated by velan module
    """
    picks = {}

    with open(PICKS_FILE_PATH, "r") as file:
        lines = [line.strip() for line in file if line.strip()]

    if not lines:
        return picks

    header = lines[0].replace("cdp=", "")
    cdp_keys = [int(val) - 1 for val in header.split(",")]

    data_lines = lines[1:]

    for i, key in enumerate(cdp_keys):
        tnmo_idx = i * 2
        vnmo_idx = i * 2 + 1

        tnmo_str = data_lines[tnmo_idx].replace("tnmo=", "")
        y_values = [float(v) for v in tnmo_str.split(",")]

        vnmo_str = data_lines[vnmo_idx].replace("vnmo=", "")
        x_values = [float(v) for v in vnmo_str.split(",")]

        picks[key] = {
            "x": x_values,
            "y": y_values
        }

    return picks
