FROM cadu21/seismic-unix:latest
WORKDIR /home/server

ENV FLASK_APP=app.create_app:create_app
ENV FLASK_RUN_HOST=0.0.0.0

COPY scripts/wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh

RUN apt update && apt upgrade -y
RUN apt install python3-pip -y

COPY . .
RUN pip install --break-system-packages -r requirements.txt
RUN chmod +x ./scripts/container_start.sh

EXPOSE 5000
CMD ["./scripts/container_start.sh"]
