import sqlalchemy as dbTypes
from os import path

from ..database.connection import database


class HelperFileLinkModel(database.Model):  # type: ignore
    """
    HelperFiles shall be stored on line domain \n
    HelperFiles can be generated by a workflow or uploaded in the line \n
    1 workflow with velan module shall produce 1 table and 1-2 model's \n
    1 workflow can have zero tables or modules \n
    """
    __tablename__ = "helper_file_link_table"

    id = dbTypes.Column(dbTypes.Integer, primary_key=True)
    path = dbTypes.Column(dbTypes.String)
    data_type = dbTypes.Column(dbTypes.String)

    lineId = dbTypes.Column(dbTypes.ForeignKey(
        "lines_table.id",
        name="FK_lines_table_helper_file_link_table",
        ondelete="CASCADE"
    ))

    created_at = dbTypes.Column(
        dbTypes.DateTime(timezone=True),
        server_default=dbTypes.func.now()
    )
    modified_at = dbTypes.Column(
        dbTypes.DateTime(timezone=True),
        onupdate=dbTypes.func.now()
    )

    def getFileName(self):
        return path.basename(self.path)

    def getAttributes(self):
        return {
            "id": self.id,
            "name": self.getFileName(),
            "path": self.path,
            "data_type": self.data_type,
            "lineId": self.lineId,
        }
