"""create-su_file_link_table

Revision ID: 3c7d80dbab65
Revises: 42656639ec6f
Create Date: 2026-01-22 00:20:37.354213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7d80dbab65'
down_revision = '42656639ec6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'su_file_link_table',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('path', sa.String(), nullable=True),
        sa.Column('projectId', sa.Integer(), nullable=True),
        sa.Column('datasetId', sa.Integer(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True
        ),
        sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['datasetId'],
            ['datasets_table.id'],
            name='FK_datasets_table_su_file_link_table',
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['projectId'],
            ['projects_table.id'],
            name='FK_projects_table_su_file_link_table',
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('su_file_link_table')
    # ### end Alembic commands ###
