"""add_lineId_column_to_file_link_table

Revision ID: 3d664fad4558
Revises: b29530f97483
Create Date: 2025-09-25 18:12:51.117616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d664fad4558'
down_revision = 'b29530f97483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_link_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lineId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK_lines_table_file_link_table', 'lines_table', ['lineId'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_link_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_lines_table_file_link_table', type_='foreignkey')
        batch_op.drop_column('lineId')

    # ### end Alembic commands ###
