"""add_post_processing_options_column_to_workflows_table

Revision ID: 42656639ec6f
Revises: 3d664fad4558
Create Date: 2025-11-08 15:23:51.273970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42656639ec6f'
down_revision = '3d664fad4558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_processing_options', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.drop_column('post_processing_options')

    # ### end Alembic commands ###
