"""add-picks_table_file_id_column-to-workflows_table

Revision ID: 4460fba479f6
Revises: d1ca37c227c8
Create Date: 2026-01-24 16:55:43.297799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4460fba479f6'
down_revision = 'd1ca37c227c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picks_table_file_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK_helper_file_link_table_workflows_table', 'helper_file_link_table', ['picks_table_file_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_helper_file_link_table_workflows_table', type_='foreignkey')
        batch_op.drop_column('picks_table_file_id')

    # ### end Alembic commands ###
