"""create-helper_file_link_table

Revision ID: c181d66b4a50
Revises: 3c7d80dbab65
Create Date: 2026-01-22 00:40:33.589429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c181d66b4a50'
down_revision = '3c7d80dbab65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'helper_file_link_table',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('path', sa.String(), nullable=True),
        sa.Column('data_type', sa.String(), nullable=True),
        sa.Column('lineId', sa.Integer(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True
        ),
        sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['lineId'],
            ['lines_table.id'],
            name='FK_lines_table_helper_file_link_table',
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('helper_file_link_table')
    # ### end Alembic commands ###
