"""delete-file_link_table

Revision ID: d1ca37c227c8
Revises: de2e902212fc
Create Date: 2026-01-22 01:38:36.454084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1ca37c227c8'
down_revision = 'de2e902212fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_link_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_link_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('datasetId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lineId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['datasetId'], ['datasets_table.id'], name=op.f('FK_datasets_table_file_link_table'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lineId'], ['lines_table.id'], name=op.f('FK_lines_table_file_link_table'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projectId'], ['projects_table.id'], name=op.f('FK_projects_table_file_link_table'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('file_link_table_pkey'))
    )
    # ### end Alembic commands ###
