"""backfill-su_file_link_table

Revision ID: de2e902212fc
Revises: c181d66b4a50
Create Date: 2026-01-22 00:54:16.232327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2e902212fc'
down_revision = 'c181d66b4a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO su_file_link_table (id, path, "projectId", created_at, modified_at)
        SELECT id, path, "projectId", created_at, modified_at
        FROM file_link_table
        WHERE "projectId" IS NOT NULL
        AND "data_type" = 'su'
        """
    )

    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'FK_su_file_links_table_workflows_table',
            'su_file_link_table',
            ['input_file_link_id'],
            ['id']
        )

    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('FK_file_links_table_workflows_table'),
            type_='foreignkey'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f('FK_file_links_table_workflows_table'),
            'file_link_table',
            ['input_file_link_id'],
            ['id']
        )

    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.drop_constraint(
            'FK_su_file_links_table_workflows_table',
            type_='foreignkey'
        )

    # ### end Alembic commands ###
