name: Run Tests
on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
      - '.github/workflows/tests.yml'
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - master
    paths:
      - 'server/**'
      - 'workspace/**'
      - 'Makefile'
      - 'docker-compose.yml'
  workflow_dispatch: {}

jobs:

  tests:
    name: Test server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Checkout fixtures
      uses: actions/checkout@v4
      with:
        repository: PETROGEO-UFRN/mock_large_files
        path: fixtures
        lfs: true

    - name: Copy fixtures
      run: |
        mkdir -p server/app/tests/mock/files/
        cp fixtures/marmousi_4ms_stack.su server/app/tests/mock/files/
        cp fixtures/marmousi_velstk_picks.dat server/app/tests/mock/files/

    - name: Install dependecies
      run: pip install -r server/requirements.txt

    - name: Install dev dependecies
      run: pip install -r server/requirements-dev.txt

    - name: Make
      run: make test

    - name: run tests
      run: cd server/ && pytest
